# Generated by Django 4.0.3 on 2022-03-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CLOTHES', 'Одежда'), ('TECH', 'Техника'), ('SERVICE', 'Услуги')], default='CLOTHES', max_length=50)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/')),
            ],
        ),
    ]
